
server:
  port: 5678

spring:
        data:
          mongodb:
            host: 10.18.55.28
            port: 10000
            username: digg_rw
            database: digg
            password: 97n9ip7Mw489952

